services:
    client:
        image: webapp-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
    server:
        image: webapp-server
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./server:/server
            - /server/node_modules