services:
    client:
        image: client
        restart: always
        ports:
            - "192.168.0.110:3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
    server:
        image: server
        restart: always
        ports:
            - "192.168.0.110:9000:9000"
        volumes:
            - ./server:/server
            - /server/node_modules